apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: es-curator-
commonLabels:
  component: es-curator
  version: v5.8.1
commonAnnotations:
  kustomization-base-url: https://github.com/4ops/kustomizations/elastic/curator
resources:
  - configmaps/config.yaml
  - configmaps/actions.yaml
  - cronjob.yaml
configMapGenerator:
  - name: env
    literals:
      - CLIENT_HOST=elasticsearch
      - CLIENT_PORT=9200
      - CLIENT_USE_SSL=False
      - CLIENT_SSL_NO_VALIDATE=False
      - CLIENT_TIMEOUT=10
      - CLIENT_MASTER_ONLY=False
      - LOGGING_LOGLEVEL=INFO
      - LOGGING_LOGFORMAT=default
generatorOptions:
  disableNameSuffixHash: true
images:
  - name: es-curator
    newName: 4ops/es-curator
    newTag: '5.8.1'
