name: Check Elastic Curator

on: [push]

jobs:
  check:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout SCM
      uses: actions/checkout@v1

    - name: Install dependencies
      env:
        BASEURL: https://storage.googleapis.com/kubernetes-release/release
      run: |
        if [ -f ./kubectl ]; then
          export KUBECTL="${PWD}/kubectl"
        else
          if kubectl version --client --short &> /dev/null; then
            export RELEASE=$(curl -s "${BASEURL}/stable.txt")
            curl -LO "${BASEURL}/${RELEASE}/bin/linux/amd64/kubectl" || exit 42
            export KUBECTL="${PWD}/kubectl"
          else
            export KUBECTL=$(which kubectl)
          fi
        fi

        test -x "${KUBECTL}" || chmod +x "${KUBECTL}"
        $KUBECTL version --short --client

    - name: Try to kustomize
      run: |
        $KUBECTL kustomize elastic/curator
